ЛР3
slava214365/LR3 pull request #1
Opened 2023-10-29 21:29 UTC by slava214365

2023-10-29 21:33 UTC, slava214365 commented
Отправил чуть позже срока, потому что не разобрался в управлении, стер половину кода в третьем задании и не смог восстановить, пришлось писать все заново.

2023-10-30 20:27 UTC, aeksei requested changes
1.5 из 3 баллов. 

---
Комментарии делятся на следующие категории:
- `GOOD` - хорошее решение. Хорошее или креативное решение.
- `TODO` - можно лучше. Эти замечания не влияют на оценку, и носят рекомендательный характер.
- `FIXME` - необходимо исправить. Устраните эти замечания, чтобы получить максимальный балл. 

---
После проверки работа, может содержать несколько статусов:
- **Changes requested**. Следует выполнить доработки, чтобы получить максимальный балл.  
	Исправление замечаний следует проводить в IDE и приложить согласно инструкции в этот pull request исправленные файлы. Файлы с исправлениями прикладывайте с теми же названиями!
- **Changes approved**. Работа выполнена на максимальный балл.  
	Рекомендуется учесть комментарии рекомендательного характера, и приложить в этот pull request исправленные файлы. В этом случае повторно на проверку присылать работу не нужно. Можно нажимать зеленую кнопку `Merge pull request`.

2023-10-30 20:27 UTC, aeksei commented on ЛР3.1.py
> +        ind = list.index(find_item)
# TODO

Тут получится сначала `in` пройдёт по элементам списка, а потом `index`. Можно сделать так, чтобы был один проход по элементам

2023-10-30 20:27 UTC, aeksei commented on ЛР3.1.py
> +    return ind
Я бы это оформил так
```python
if find_item in items_list:
    ind = list.index(find_item)
    return ind
```

2023-10-30 20:27 UTC, aeksei commented on ЛР3.1.py
1 балл

2023-10-30 20:27 UTC, aeksei commented on ЛР3.2.py
> +            common_people.append(people)
# FIXME
Заменить на метод `intersection` у списков

2023-10-30 20:27 UTC, aeksei commented on ЛР3.2.py
0.5 балла

2023-10-30 20:27 UTC, aeksei commented on ЛР3.3.py
> +        if letter.isalpha() != False:
# FIXME 
Просто `if letter.isalpha():`
![image](https://github.com/slava214365/LR3/assets/14962819/4782ac93-21f6-42a0-ac34-c508e5ee8155)

2023-10-30 20:27 UTC, aeksei commented on ЛР3.3.py
> +        sum += glossary[letter]
# FIXME
1. `sum` - встроенная команда, так лучше не называть переменные
2. А этот момент лучше заменить на `sum_ = sum(glossary.values())`

2023-10-30 20:28 UTC, aeksei commented
> Отправил чуть позже срока, потому что не разобрался в управлении, стер половину кода в третьем задании и не смог восстановить, пришлось писать все заново.

Штраф при отправке после жёсткого дедлайна

2023-11-03 16:13 UTC, aeksei approved these changes
Максимальный балл

---
Комментарии делятся на следующие категории:
- `GOOD` - хорошее решение. Хорошее или креативное решение.
- `TODO` - можно лучше. Эти замечания не влияют на оценку, и носят рекомендательный характер.
- `FIXME` - необходимо исправить. Устраните эти замечания, чтобы получить максимальный балл. 

---
После проверки работа, может содержать несколько статусов:
- **Changes requested**. Следует выполнить доработки, чтобы получить максимальный балл.  
	Исправление замечаний следует проводить в IDE и приложить согласно инструкции в этот pull request исправленные файлы. Файлы с исправлениями прикладывайте с теми же названиями!
- **Changes approved**. Работа выполнена на максимальный балл.  
	Рекомендуется учесть комментарии рекомендательного характера, и приложить в этот pull request исправленные файлы. В этом случае повторно на проверку присылать работу не нужно. Можно нажимать зеленую кнопку `Merge pull request`.

2023-11-03 20:43 UTC, merged